---
title: "p8105_hw1_isn2102"
author: Isabel S Nelson
output: github_document
---

Setup: load libraries
```{r}
library(tidyverse)
```

#### Problem 1: 
Create a data frame.
Shortcut for inserting r code chunk is option+command+i

```{r dataframe} 
prob1_df <- # Use <- outside of functions and = within functions
  tibble(
    samp = rnorm(10), 
    samp_greater = samp > 0, 
    char_vec = c("hi", "my", "name", "is", "Isabel", "and", "I", "live", "in", "Harlem"), 
    fac_vec = factor(c("small", "medium", "large", "small", "medium", "large", "small", "medium", "large", "small"))
)
```

Take the mean of each variable in the data frame.
```{r mean}
# Use pull(df, variable) to pull column from a tibble in tidyverse
mean(pull(prob1_df, samp))
mean(pull(prob1_df, samp_greater))
mean(pull(prob1_df, char_vec)) # Cannot get mean of a character
mean(pull(prob1_df, fac_vec)) # Cannot get mean of a factor
```

I can get the mean of numbers and logical vectors but not characters or factors. 
```{r numeric_convert}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, samp_greater))
as.numeric(pull(prob1_df, char_vec)) 
as.numeric(pull(prob1_df, fac_vec))
```

```{r}
as.numeric(pull(prob1_df, samp_greater)) * pull(prob1_df, samp)
```


#### Problem 2: 

```{r}

```

